apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    tier: web1
spec:
  selector:
    matchLabels:
      app: nginx
      tier: web1
  replicas: 5 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
        tier: web1
    spec:
      containers:
      - name: nginx
        image: apfol98/nginx-proxy:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      - name: web1
        image: apfol98/web1:latest