version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.0.0
jobs:
  verify-install:
    executor: azure-cli/default
    steps:
      - azure-cli/install
      - run:
          command: az -v
          name: Verify Azure CLI is installed
  login-to-azure:
    executor: azure-cli/azure-docker
    steps:
      - run:
          command: az login -u andresram@unisabana.edu.co -p APFol9824XD
          name: Sign In to Azure CLI
      - run:
          command: az aks get-credentials --resource-group Ubuntu --name cluster
          name: Connect to cluster using kubectl
      - run:
          command: kubectl config get-contexts
          name: Show all the clusters
workflows:
  example-workflow:
    jobs:
      - login-to-azure