version: 2.1
orbs:
  azure-aks: circleci/azure-aks@0.2.1
jobs:
  login-and-development-deploy:
    executor: azure-aks/azure-docker
    steps:
      - checkout
      - run:
          command: az login -u ${USER} -p ${PASS}
          name: Sign In to Azure CLI
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: cluster
          install-kubectl: true
          resource-group: Ubuntu
      - run:
          command: kubectl apply -f web1.yaml --namespace ingress-basic
          name: Apply new deployment to web 1
      - run:
          command: kubectl apply -f web2.yaml --namespace ingress-basic
          name: Apply new deployment to web 2
      - run:
          command: kubectl apply -f web-default.yaml --namespace ingress-basic
          name: Apply new deployment to web default
  approval-job:
  login-and-production-deploy:
    executor: azure-aks/azure-docker
    steps:
      - checkout
      - run:
          command: az login -u ${USER} -p ${PASS}
          name: Sign In to Azure CLI
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: production
          install-kubectl: true
          resource-group: Produc
      - run:
          command: kubectl apply -f web1.yaml --namespace ingress-basic
          name: Apply new deployment to web 1
      - run:
          command: kubectl apply -f web2.yaml --namespace ingress-basic
          name: Apply new deployment to web 2
      - run:
          command: kubectl apply -f web-default.yaml --namespace ingress-basic
          name: Apply new deployment to web default
workflows:
  build-and-test:
    jobs:
      - login-and-development-deploy:
          filters:
              branches:
                  only: circleci-project-setup
      - approval-job:
          type: approval
          requires:
              - login-and-development-deploy
          filters:
            branches:
                only: circleci-project-setup
      - login-and-production-deploy:
          filters:
              branches:
                  only: circleci-project-setup
          requires:
              - approval-job